export const characterData = [
	{
		weightClass: 'light',
		character: 'Baby Peach',
		speedNormal: 2.25,
		speedAntigravity: 2,
		speedWater: 2.5,
		speedAir: 2.75,
		acceleration: 4,
		weight: 2,
		handlingNormal: 5,
		handlingAntigravity: 5,
		handlingWater: 4.5,
		handlingAir: 5,
		grip: 4.25,
		miniTurbo: 4,
	},
	{
		weightClass: 'light',
		character: 'Baby Daisy',
		speedNormal: 2.25,
		speedAntigravity: 2,
		speedWater: 2.5,
		speedAir: 2.75,
		acceleration: 4,
		weight: 2,
		handlingNormal: 5,
		handlingAntigravity: 5,
		handlingWater: 4.5,
		handlingAir: 5,
		grip: 4.25,
		miniTurbo: 4,
	},
	{
		weightClass: 'light',
		character: 'Baby Rosalina',
		speedNormal: 2.25,
		speedAntigravity: 2,
		speedWater: 2.5,
		speedAir: 2.75,
		acceleration: 4.25,
		weight: 2,
		handlingNormal: 4.75,
		handlingAntigravity: 4.75,
		handlingWater: 4.25,
		handlingAir: 4.75,
		grip: 3.75,
		miniTurbo: 4,
	},
	{
		weightClass: 'light',
		character: 'Lemmy',
		speedNormal: 2.25,
		speedAntigravity: 2,
		speedWater: 2.5,
		speedAir: 2.75,
		acceleration: 4.25,
		weight: 2,
		handlingNormal: 4.75,
		handlingAntigravity: 4.75,
		handlingWater: 4.25,
		handlingAir: 4.75,
		grip: 3.75,
		miniTurbo: 4,
	},
	{
		weightClass: 'light',
		character: 'Baby Mario',
		speedNormal: 2.5,
		speedAntigravity: 2.25,
		speedWater: 2.75,
		speedAir: 3,
		acceleration: 4.25,
		weight: 2.25,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Baby Luigi',
		speedNormal: 2.5,
		speedAntigravity: 2.25,
		speedWater: 2.75,
		speedAir: 3,
		acceleration: 4.25,
		weight: 2.25,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Dry Bones',
		speedNormal: 2.5,
		speedAntigravity: 2.25,
		speedWater: 2.75,
		speedAir: 3,
		acceleration: 4.25,
		weight: 2.25,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Light Mii',
		speedNormal: 2.5,
		speedAntigravity: 2.25,
		speedWater: 2.75,
		speedAir: 3,
		acceleration: 4.25,
		weight: 2.25,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Koopa Troopa',
		speedNormal: 2.75,
		speedAntigravity: 2.5,
		speedWater: 3,
		speedAir: 3.25,
		acceleration: 4,
		weight: 2.5,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4.25,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Lakitu',
		speedNormal: 2.75,
		speedAntigravity: 2.5,
		speedWater: 3,
		speedAir: 3.25,
		acceleration: 4,
		weight: 2.5,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4.25,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Bowser Jr.',
		speedNormal: 2.75,
		speedAntigravity: 2.5,
		speedWater: 3,
		speedAir: 3.25,
		acceleration: 4,
		weight: 2.5,
		handlingNormal: 4.5,
		handlingAntigravity: 4.5,
		handlingWater: 4,
		handlingAir: 4.5,
		grip: 4.25,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Toadette',
		speedNormal: 2.75,
		speedAntigravity: 2.5,
		speedWater: 3,
		speedAir: 3.25,
		acceleration: 4.25,
		weight: 2.5,
		handlingNormal: 4.25,
		handlingAntigravity: 4.25,
		handlingWater: 3.75,
		handlingAir: 4.25,
		grip: 3.5,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Wendy',
		speedNormal: 2.75,
		speedAntigravity: 2.5,
		speedWater: 3,
		speedAir: 3.25,
		acceleration: 4.25,
		weight: 2.5,
		handlingNormal: 4.25,
		handlingAntigravity: 4.25,
		handlingWater: 3.75,
		handlingAir: 4.25,
		grip: 3.5,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Isabelle',
		speedNormal: 2.75,
		speedAntigravity: 2.5,
		speedWater: 3,
		speedAir: 3.25,
		acceleration: 4.25,
		weight: 2.5,
		handlingNormal: 4.25,
		handlingAntigravity: 4.25,
		handlingWater: 3.75,
		handlingAir: 4.25,
		grip: 3.5,
		miniTurbo: 3.75,
	},
	{
		weightClass: 'light',
		character: 'Toad',
		speedNormal: 3,
		speedAntigravity: 2.75,
		speedWater: 3.25,
		speedAir: 3.5,
		acceleration: 4,
		weight: 2.75,
		handlingNormal: 4.25,
		handlingAntigravity: 4.25,
		handlingWater: 3.75,
		handlingAir: 4.25,
		grip: 4,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'light',
		character: 'Shy Guy',
		speedNormal: 3,
		speedAntigravity: 2.75,
		speedWater: 3.25,
		speedAir: 3.5,
		acceleration: 4,
		weight: 2.75,
		handlingNormal: 4.25,
		handlingAntigravity: 4.25,
		handlingWater: 3.75,
		handlingAir: 4.25,
		grip: 4,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'light',
		character: 'Larry',
		speedNormal: 3,
		speedAntigravity: 2.75,
		speedWater: 3.25,
		speedAir: 3.5,
		acceleration: 4,
		weight: 2.75,
		handlingNormal: 4.25,
		handlingAntigravity: 4.25,
		handlingWater: 3.75,
		handlingAir: 4.25,
		grip: 4,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Cat Peach',
		speedNormal: 3.25,
		speedAntigravity: 3,
		speedWater: 3.5,
		speedAir: 3.75,
		acceleration: 4,
		weight: 2.75,
		handlingNormal: 4,
		handlingAntigravity: 4,
		handlingWater: 3.5,
		handlingAir: 4,
		grip: 3.75,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Inkling Girl',
		speedNormal: 3.25,
		speedAntigravity: 3,
		speedWater: 3.5,
		speedAir: 3.75,
		acceleration: 4,
		weight: 2.75,
		handlingNormal: 4,
		handlingAntigravity: 4,
		handlingWater: 3.5,
		handlingAir: 4,
		grip: 3.75,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Female Villager',
		speedNormal: 3.25,
		speedAntigravity: 3,
		speedWater: 3.5,
		speedAir: 3.75,
		acceleration: 4,
		weight: 2.75,
		handlingNormal: 4,
		handlingAntigravity: 4,
		handlingWater: 3.5,
		handlingAir: 4,
		grip: 3.75,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Peach',
		speedNormal: 3.5,
		speedAntigravity: 3.25,
		speedWater: 3.75,
		speedAir: 4,
		acceleration: 3.75,
		weight: 3,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.75,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Daisy',
		speedNormal: 3.5,
		speedAntigravity: 3.25,
		speedWater: 3.75,
		speedAir: 4,
		acceleration: 3.75,
		weight: 3,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.75,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Yoshi',
		speedNormal: 3.5,
		speedAntigravity: 3.25,
		speedWater: 3.75,
		speedAir: 4,
		acceleration: 3.75,
		weight: 3,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.75,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Tanooki Mario',
		speedNormal: 3.5,
		speedAntigravity: 3.25,
		speedWater: 3.75,
		speedAir: 4,
		acceleration: 3.75,
		weight: 3.25,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.25,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Inkling Boy',
		speedNormal: 3.5,
		speedAntigravity: 3.25,
		speedWater: 3.75,
		speedAir: 4,
		acceleration: 3.75,
		weight: 3.25,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.25,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Male Villager',
		speedNormal: 3.5,
		speedAntigravity: 3.25,
		speedWater: 3.75,
		speedAir: 4,
		acceleration: 3.75,
		weight: 3.25,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.25,
		miniTurbo: 3.5,
	},
	{
		weightClass: 'medium',
		character: 'Luigi',
		speedNormal: 3.75,
		speedAntigravity: 3.5,
		speedWater: 4,
		speedAir: 4.25,
		acceleration: 3.5,
		weight: 3.5,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.25,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'medium',
		character: 'Iggy',
		speedNormal: 3.75,
		speedAntigravity: 3.5,
		speedWater: 4,
		speedAir: 4.25,
		acceleration: 3.5,
		weight: 3.5,
		handlingNormal: 3.75,
		handlingAntigravity: 3.75,
		handlingWater: 3.25,
		handlingAir: 3.75,
		grip: 3.25,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'medium',
		character: 'Mario',
		speedNormal: 3.75,
		speedAntigravity: 3.5,
		speedWater: 4,
		speedAir: 4.25,
		acceleration: 3.5,
		weight: 3.5,
		handlingNormal: 3.5,
		handlingAntigravity: 3.5,
		handlingWater: 3,
		handlingAir: 3.5,
		grip: 3.5,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'medium',
		character: 'Ludwig',
		speedNormal: 3.75,
		speedAntigravity: 3.5,
		speedWater: 4,
		speedAir: 4.25,
		acceleration: 3.5,
		weight: 3.5,
		handlingNormal: 3.5,
		handlingAntigravity: 3.5,
		handlingWater: 3,
		handlingAir: 3.5,
		grip: 3.5,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'medium',
		character: 'Medium Mii',
		speedNormal: 3.75,
		speedAntigravity: 3.5,
		speedWater: 4,
		speedAir: 4.25,
		acceleration: 3.5,
		weight: 3.5,
		handlingNormal: 3.5,
		handlingAntigravity: 3.5,
		handlingWater: 3,
		handlingAir: 3.5,
		grip: 3.5,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'heavy',
		character: 'Rosalina',
		speedNormal: 4,
		speedAntigravity: 3.75,
		speedWater: 4.25,
		speedAir: 4.5,
		acceleration: 3.25,
		weight: 3.75,
		handlingNormal: 3.25,
		handlingAntigravity: 3.25,
		handlingWater: 2.75,
		handlingAir: 3.25,
		grip: 3.75,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'heavy',
		character: 'King Boo',
		speedNormal: 4,
		speedAntigravity: 3.75,
		speedWater: 4.25,
		speedAir: 4.5,
		acceleration: 3.25,
		weight: 3.75,
		handlingNormal: 3.25,
		handlingAntigravity: 3.25,
		handlingWater: 2.75,
		handlingAir: 3.25,
		grip: 3.75,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'heavy',
		character: 'Link',
		speedNormal: 4,
		speedAntigravity: 3.75,
		speedWater: 4.25,
		speedAir: 4.5,
		acceleration: 3.25,
		weight: 3.75,
		handlingNormal: 3.25,
		handlingAntigravity: 3.25,
		handlingWater: 2.75,
		handlingAir: 3.25,
		grip: 3.75,
		miniTurbo: 3.25,
	},
	{
		weightClass: 'heavy',
		character: 'Metal Mario',
		speedNormal: 4.25,
		speedAntigravity: 4,
		speedWater: 4.5,
		speedAir: 4.75,
		acceleration: 3.25,
		weight: 4.5,
		handlingNormal: 3.25,
		handlingAntigravity: 3.25,
		handlingWater: 2.75,
		handlingAir: 3.25,
		grip: 3,
		miniTurbo: 3,
	},
	{
		weightClass: 'heavy',
		character: 'Gold Mario',
		speedNormal: 4.25,
		speedAntigravity: 4,
		speedWater: 4.5,
		speedAir: 4.75,
		acceleration: 3.25,
		weight: 4.5,
		handlingNormal: 3.25,
		handlingAntigravity: 3.25,
		handlingWater: 2.75,
		handlingAir: 3.25,
		grip: 3,
		miniTurbo: 3,
	},
	{
		weightClass: 'heavy',
		character: 'Pink Gold Peach',
		speedNormal: 4.25,
		speedAntigravity: 4,
		speedWater: 4.5,
		speedAir: 4.75,
		acceleration: 3.25,
		weight: 4.5,
		handlingNormal: 3.25,
		handlingAntigravity: 3.25,
		handlingWater: 2.75,
		handlingAir: 3.25,
		grip: 3,
		miniTurbo: 3,
	},
	{
		weightClass: 'heavy',
		character: 'Waluigi',
		speedNormal: 4.5,
		speedAntigravity: 4.25,
		speedWater: 4.75,
		speedAir: 5,
		acceleration: 3.25,
		weight: 4,
		handlingNormal: 3,
		handlingAntigravity: 3,
		handlingWater: 2.5,
		handlingAir: 3,
		grip: 3,
		miniTurbo: 3,
	},
	{
		weightClass: 'heavy',
		character: 'Donkey Kong',
		speedNormal: 4.5,
		speedAntigravity: 4.25,
		speedWater: 4.75,
		speedAir: 5,
		acceleration: 3.25,
		weight: 4,
		handlingNormal: 3,
		handlingAntigravity: 3,
		handlingWater: 2.5,
		handlingAir: 3,
		grip: 3,
		miniTurbo: 3,
	},
	{
		weightClass: 'heavy',
		character: 'Roy',
		speedNormal: 4.5,
		speedAntigravity: 4.25,
		speedWater: 4.75,
		speedAir: 5,
		acceleration: 3.25,
		weight: 4,
		handlingNormal: 3,
		handlingAntigravity: 3,
		handlingWater: 2.5,
		handlingAir: 3,
		grip: 3,
		miniTurbo: 3,
	},
	{
		weightClass: 'heavy',
		character: 'Wario',
		speedNormal: 4.75,
		speedAntigravity: 4.5,
		speedWater: 5,
		speedAir: 5.25,
		acceleration: 3,
		weight: 4.25,
		handlingNormal: 2.75,
		handlingAntigravity: 2.75,
		handlingWater: 2.25,
		handlingAir: 2.75,
		grip: 3.25,
		miniTurbo: 2.75,
	},
	{
		weightClass: 'heavy',
		character: 'Dry Bowser',
		speedNormal: 4.75,
		speedAntigravity: 4.5,
		speedWater: 5,
		speedAir: 5.25,
		acceleration: 3,
		weight: 4.25,
		handlingNormal: 2.75,
		handlingAntigravity: 2.75,
		handlingWater: 2.25,
		handlingAir: 2.75,
		grip: 3.25,
		miniTurbo: 2.75,
	},
	{
		weightClass: 'heavy',
		character: 'Bowser',
		speedNormal: 4.75,
		speedAntigravity: 4.5,
		speedWater: 5,
		speedAir: 5.25,
		acceleration: 3,
		weight: 4.5,
		handlingNormal: 2.5,
		handlingAntigravity: 2.5,
		handlingWater: 2,
		handlingAir: 2.5,
		grip: 3,
		miniTurbo: 2.75,
	},
	{
		weightClass: 'heavy',
		character: 'Morton',
		speedNormal: 4.75,
		speedAntigravity: 4.5,
		speedWater: 5,
		speedAir: 5.25,
		acceleration: 3,
		weight: 4.5,
		handlingNormal: 2.5,
		handlingAntigravity: 2.5,
		handlingWater: 2,
		handlingAir: 2.5,
		grip: 3,
		miniTurbo: 2.75,
	},
	{
		weightClass: 'heavy',
		character: 'Heavy Mii',
		speedNormal: 4.75,
		speedAntigravity: 4.5,
		speedWater: 5,
		speedAir: 5.25,
		acceleration: 3,
		weight: 4.5,
		handlingNormal: 2.5,
		handlingAntigravity: 2.5,
		handlingWater: 2,
		handlingAir: 2.5,
		grip: 3,
		miniTurbo: 2.75,
	},
];
